### ISSUE TITLE
Link at the bottom URL does not work correctly

### ISSUE THREAD

**Issue by McFarts** [LowEndNetwork/FeedbackAndIssues#1]
The 'Vanilla' link at the bottom goes to:

http://www.lowendtalk.com/web/20130502114727/http://vanillaforums.org/

Which is a page not found

**Comment by mpkossen** [comment]
Thanks for taking the time to report this. This is a theme issue and will be fixed soon.

**Comment by mpkossen** [comment]
This has been fixed.
