### ISSUE TITLE
Initiate Top Provider Poll 2015-Q1/2

### ISSUE THREAD

**Issue by ridgewell** [LowEndNetwork/FeedbackAndIssues#3]
It's been said that the Top Provider polls have been run, and 2 or 5 months past the date they were promised to be run. It was one of the better resources provided by LowEndBox. Several of the providers in the Top Providers, 2014 Q3 have stopped running (and been acquired), no longer advertise on the LEB/LET network, or have simply gone downhill, while other providers have earned the respect of those within the community.

Please bring back the Top Provider polls. They were always nice to have.

Thanks.

**Comment by mpkossen** [comment]
The return of the poll has been on the agenda for a while and will happen. You will see it return soon enough.
